dotnet sln add cephes/z0.cephes.csproj
dotnet sln add libm/z0.libm.csproj
dotnet sln add test/z0.mathlibs.test.csproj
dotnet sln add ../structs/z0.structs.csproj
dotnet sln add ../nats/z0.nats.csproj
dotnet sln add ../func/z0.zfunc.csproj
dotnet sln add ../primal/z0.primal.csproj
dotnet sln add ../rng/src/core/z0.rng.core.csproj
dotnet sln add ../testing/z0.testing.csproj
