dotnet sln add ../structs/z0.structs.csproj
dotnet sln add ../nats/z0.nats.csproj
dotnet sln add ../func/z0.zfunc.csproj
dotnet sln add ../matrix/src/z0.matrix.csproj
dotnet sln add ../primal/z0.primal.csproj
dotnet sln add ../inx/src/core/z0.inx.core.csproj
dotnet sln add ../rng/src/core/z0.rng.core.csproj
dotnet sln add ../testing/z0.testing.csproj
dotnet sln add src/z0.linear.csproj